### PR TITLE
Add drop down menu for calendar selection, add checkbox for JIAYOU dates, fix events disappearing when edited

### LINKED ISSUE #2: Events disappear when edited for "this and following events"
@jmarmstrong1207 

A fellow colleague brought to my attention, and I was able to replicate, that events disappear when edited for "this and following events." You can still search for them, but they no longer display on the calendar.
I tried editing one event and saving for all events, nevertheless some events still won't display on the calendar...it's as if they enter a void. (Yes, we can still search and delete all events as a series, but...)

Additional testing: Events don't disappear when edited for "this event" or "all events." 
In fact, the events stay chained. I can edit an event that has a different title than all other events, save the edit for all events, and its and all the other events' titles change in tandem.

Are you able to replicate this, too?
I tested using your merged commit (2baccd2e3e1f2aee58c7a5fc524e6ee531c35c86) and my latest commit (639ae6f654e2ce9e6b8ea6193905e83b5fa5f36d), same outcome

### PR DESCRIPTION
**Pull request by jmarmstrong1207**
fixes #2.

CAIS prefers to use just calendar, no altcalendar, so I have removed that as well

### CODE REVIEW

**Comment by saegl5** [comment]
@jmarmstrong1207 
thanks for the new pull request :)
sorry to trouble you, but could you possibly rebase first?

I pulled the merge request to review it but got divergent branches

**Comment by saegl5** [comment]
> fixes #2.
> 
> CAIS prefers to use just calendar, no altcalendar, so I have removed that as well

"calendar" is the reference calendar, that is the one that has the cycling letter days (e.g., Internal Calendar)
"altcalendar" is an optional calendar, potentially a single user's calendar (e.g., FirstName_LastName)

for a single user, he/she/they/non-binary _can_ add events to the "calendar," no problem

for a business/organization, however, multiple users adding events to the [same] "calendar," I imagine this may render the "calendar" messy
...multiple users adding events to their own "altcalendar" should be cleaner

**Comment by jmarmstrong1207** [comment]
You're right, altcalendar is a better solution

**Comment by jmarmstrong1207** [comment]
There's really only one reference calendar we have for jiayou dates, so I hard-coded it. Makes it easier for end users to add events.

Rebasing was more difficult as we have some conflicting code and multiple implementations of the same thing, so I replace the entire code.gs file with what I had

**Comment by jmarmstrong1207** [comment]
I think the all day events have to fixed again, I’ll do that soon

**Comment by saegl5** [comment]
@jmarmstrong1207
okay, I reviewed all the changes, looks great 👍 
I plan to merge, touch things up (e.g., add note-to-self comments), then push

`[...document.querySelectorAll('input[name=query]:checked')].map(({value}) => value)` was overall very enlightening

**Comment by jmarmstrong1207** [comment]
yeah I had to google that lmao

https://stackoverflow.com/questions/2600343/why-does-document-queryselectorall-return-a-staticnodelist-rather-than-a-real-ar

**Comment by saegl5** [comment]
STATUS:

- [x] merged (locally)
- [x] touching up...
  - [x] README.md
  - [x] Index.html
  - [x] Code.gs
  - [x] screenshot
  - [x] license
- [x] testing Successful! 
- [x] sorting through notes
- [x] pulling two recent commits
- [x] fixing conflicts
- [x] pushing
- [x] realign dev branch: note to self---`git checkout development && git merge --no-ff main`

**Pull request merged**
